### ISSUE TITLE
How do flutter & Unreal send data to each other?

### ISSUE THREAD

**Issue by futouyiba** [BlzFans/FlutterUnreal#2]

**Comment by BlzFans** [comment]
You can use lua as an intermediate language
Unreal --> Lua --> Dart
Dart --> Lua --> Unreal

Or directly use C++ and Dart to call each other.

dart call cpp example:
https://github.com/BlzFans/FlutterUnreal/blob/main/examples/packages/flutter_unreal/lib/lua_utils.dart

cpp call dart example:
UnrealDemo/Plugins/FlutterUnreal/Source/Private/FlutterEmbeder.cpp 
cpp function int64_t testDartCallCpp(int64_t i, int64_t j)
called from Dart examples/packages/flutter_unreal/lib/flutter_unreal.dart: void initFlutterUnreal()

**Comment by futouyiba** [comment]
Thank you BlzFans!
